<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daily Trends</title>
    <link rel="icon" href="../assest/news.ico" type="image/x-icon" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
<body>
  <div class="container">
    <div class="page-header">
      <h2>New Feed</h2>
    </div>
    <form method="POST" action="./" enctype="multipart/form-data">
	<!-- COMPONENT START -->
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="title">
      </div>
      <div class="form-group">
        <label for="body">Body:</label>
        <input type="text" class="form-control" id="body" name="body">
      </div>
      <div class="form-group">
        <label for="source">Source:</label>
        <input type="text" class="form-control" id="source" name="source">
      </div>
      <div class="form-group">
        <label for="publisher">Publisher:</label>
        <input type="text" class="form-control" id="publisher" name="publisher">
      </div>

      <div class="form-group">
    		<div class="input-group input-file">
        		<input type="file" class="form-control"
            placeholder='Choose a file...' name="image" />
        		<span class="input-group-btn">
        		</span>
    		</div>
    	</div>

      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <?php if($data != null) echo $data;?>
  </div>
</body>
<html>
