<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daily Trends</title>
    <link rel="icon" href="../assest/news.ico" type="image/x-icon" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
<body>
  <div class="container">
    <h1>Daily Trends</h1>
    <div class="text-right">
        <a href="./?new=feed" class="btn btn-success">Add Feed</a>
    </div>
      <h3>Users News</h3>
      <hr/>
    <?php foreach($data as $feed) { ?>

    <div class="well">
      <div class="media">
      	<a class="pull-left" href="#">
    		<img class="media-object" src="<?php echo $feed["image"];?>">
  		</a>
  		<div class="media-body">
    		<h4 class="media-heading">
            <?php echo $feed["title"]; ?>
        </h4>
          <p class="text-right"><?php echo $feed["publisher"]; ?></p>
          <p><?php echo $feed["body"];?></p>
          <ul class="list-inline list-unstyled">
  			    <li>
             <?php echo $feed["source"];?>
           </li>
			   </ul>
         <div class="text-right">
             <a href="/controllers/DeletFeedController.php" class="btn btn-danger">Delete</a>
         </div>
       </div>
    </div>
  </div>
<?php } ?>

  </div>
</body>
<html>
