<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daily Trends</title>
    <link rel="icon" href="assets/news.ico" type="image/x-icon" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="libs/jquery.tmpl.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
<body>
  <div class="container">
    <h1>Daily Trends</h1>
    <div class="text-right">
        <a href="./?new=feed" class="btn btn-success">Add Feed</a>
    </div>
    <div id="el-pais">
      <h2> El País feeds</h2>
      <h3 id="loading-pais">Loading <img src="assets/loading.gif"></h3>
    </div>
    <div id="el-mundo">
      <h2> El Mundo feeds</h2>
      <h3 id="loading-mundo">Loading <img src="assets/loading.gif"></h3>
    </div>
      <h2>Users feeds</h2>
      <hr/>
    <?php foreach($dataDataBase as $feed) { ?>

    <div class="well">
      <div class="media">
      	<a class="pull-left" href="#">
    		<img class="media-object" src="assets/images/<?php echo $feed["image"];?>">
  		</a>
  		<div class="media-body">
    		<h3 class="media-heading">
            <?php echo $feed["title"]; ?>
        </h3>
          <p class="text-right"><?php echo $feed["publisher"]; ?></p>
          <p><?php echo $feed["body"];?></p>
          <ul class="list-inline list-unstyled">
  			    <li>
             <?php echo $feed["source"];?>
           </li>
			   </ul>
         <div class="text-right">
             <form action="./"
               method="POST">
               <input type="hidden" name="delete"
               value="<?php echo $feed["id"];?>" >
               <button type="submit" class="btn btn-danger">Delete</button>
            </form>
         </div>
       </div>
    </div>
  </div>
<?php } ?>

  </div>
  <script type="text/javascript">
    "use strict";
    (function(){
      function ajaxRequest(newspaper){
        $.ajax({
          url : './index.php?'+newspaper,
          type : 'GET',
          dataType : 'json',
          success : function(data) {
            console.log('datos', data);
              if (data[0].source === 'El País')
              {
                $('#loading-pais').hide();
              }else {
                $('#loading-mundo').hide();
              }

              $.get('./views/template.feeds.html', function(template){
                console.log("template", template);
                $.tmpl(template, data).appendTo('#el-'+newspaper);
            });
          },
          error : function(xhr, status) {
              console.log('request error',status);
          },

          complete : function(xhr, status) {
              console.log('request done',status);
          }
        });
      }


    ajaxRequest('pais');
    ajaxRequest('mundo');

  })();
    function hide(id){
       document.getElementById('d'+id).style.display='none';
    }
  </script>
</body>
<html>
